### ISSUE TITLE
Which of the following are TRUE?

### ISSUE THREAD

**Issue by izxi** [izxi/Learning#6]
Which of the following are TRUE?

Select one or more:

- [ ] - A. Only structured data can be visualized
- [x] - B. Tableau is a good visualization tool
- [x] - C. R has many good visualization packages
- [x] - D. Data preparation is a necessary step for visualization

**Comment by izxi** [comment]
[Data Visualization Is Key To Analyzing Unstructured Data](https://www.logtrust.com/data-visualization-key-analyzing-unstructured-data/)

**Comment by izxi** [comment]
[tableau](https://www.tableau.com/trial/data-visualization)

**Comment by izxi** [comment]
[Great R packages for data import, wrangling and visualization](https://www.computerworld.com/article/2921176/business-intelligence/great-r-packages-for-data-import-wrangling-visualization.html)

**Comment by izxi** [comment]
[Data preparation](https://www.datawatch.com/2015/05/12/data-preparation-a-necessary-step-an-annoying-hurdle/)

**Comment by johnnieng** [comment]
B. Tableau is a good visualization tool
 C. R has many good visualization packages
 D. Data preparation is a necessary step for visualization *

**Comment by mebriki** [comment]
[3. Clean your data](https://guides.lib.uoguelph.ca/c.php)

This is an essential step to perform before creating a visualization. Clean, consistent data _**will be much easier to visualize**_.

Clean data is data that is free of errors or anomalies which may make it hard to use or analyze the data. Starting from a clean dataset allows you to focus on **_creating an effective visualization_** rather than trying to diagnose and and fix issues while creating visualizations.
